Add PlonkVeriferOnICP in
dfinity/awesome-internet-computer pull request #171
Opened 2024-10-08 07:22 UTC by readygo67

2024-10-14 08:10 UTC, domwoe requested changes

2024-10-14 08:10 UTC, domwoe commented on README.md
> +- [Ganrk Plonk Verifer](https://github.com/lightec-xyz/plonk_verifier_on_icp) - A Canister that can verify proof generated by [gnark](https://github.com/Consensys/gnark) on the BN254 curve，is a cruci
```suggestion
- [Gnark Plonk Verifer](https://github.com/lightec-xyz/plonk_verifier_on_icp) - A Canister that can verify proofs generated by [gnark](https://github.com/Consensys/gnark) on the BN254 curve.
```

2024-10-30 10:38 UTC, domwoe commented on README.md
> +- [Ganrk Plonk Verifer](https://github.com/lightec-xyz/plonk_verifier_on_icp) - A Canister that can verify proof generated by [gnark](https://github.com/Consensys/gnark) on the BN254 curve，is a cruci
```suggestion
- [Gnark Plonk Verifer](https://github.com/lightec-xyz/plonk_verifier_on_icp) - A Canister that can verify proofs generated by [gnark](https://github.com/Consensys/gnark) on the BN254 curve.
```

2024-10-30 10:40 UTC, domwoe commented on README.md
> +- [Ganrk Plonk Verifer](https://github.com/lightec-xyz/plonk_verifier_on_icp) - A Canister that can verify proof generated by [gnark](https://github.com/Consensys/gnark) on the BN254 curve，is a cruci
@readygo67 Could you please accept this change?

2025-02-14 03:49 UTC, readygo67 commented on README.md
> +- [Ganrk Plonk Verifer](https://github.com/lightec-xyz/plonk_verifier_on_icp) - A Canister that can verify proof generated by [gnark](https://github.com/Consensys/gnark) on the BN254 curve，is a cruci
Yes, it's ok to make such modification

2025-03-20 01:44 UTC, closed without merging